apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "Build and Deploy template for Quarkus applications built using a Tekton Pipeline"
    iconClass: icon-java
    openshift.io/display-name: "Quarkus JVM Build & Deploy Pipeline for DEV"
    template.openshift.io/bindable: "false"
    tags: "java,quarkus"
    version: "1.0"
  name: quarkus-jvm-pipeline-dev
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: "${APP_NAME}"
      name: "${APP_NAME}"
    spec:
      lookupPolicy:
        local: false

  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: ${APP_NAME} Quarkus JVM Service.
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        deploymentConfig: ${APP_NAME}

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        description: ${APP_NAME} Quarkus JVM Deployment Configuration.
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      replicas: 0
      selector:
        deploymentConfig: ${APP_NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            deploymentConfig: ${APP_NAME}
          name: ${APP_NAME}
        spec:
          initContainers:
          - args:
              - '-c'
              - >-
                cd /tmp && csplit -z -f crt- $ca_bundle '/-----BEGIN CERTIFICATE-----/' '{*}'
                && for file in crt-*; do keytool -import -noprompt -keystore
                $truststore_jks -file $file -storepass $password -alias
                service-$file; done
            command:
              - /bin/bash
            env:
              - name: ca_bundle
                value: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
              - name: truststore_jks
                value: /var/run/secrets/java.io/keystores/truststore.jks
              - name: password
                value: changeit
            image: 'image-registry.openshift-image-registry.svc:5000/openshift/jdk-ubi-minimal:8.1'
            imagePullPolicy: IfNotPresent
            name: pem-to-truststore
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /var/run/secrets/java.io/keystores
                name: keystore-volume
          containers: 
          - env:
            - name: JAVA_OPTIONS
              value: '-Djavax.net.ssl.trustStore=/var/run/secrets/java.io/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit'
            envFrom:
            - configMapRef:
                name: ${APP_NAME}-cm 
            - secretRef:
                name: ${APP_NAME}-sk
            image: image-registry.openshift-image-registry.svc:5000/rating/${APP_NAME}
            imagePullPolicy: Always
            name: ${APP_NAME}
            ports:
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
            volumeMounts:
            - mountPath: /var/run/secrets/java.io/keystores
              name: keystore-volume
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              periodSeconds: 20
              successThreshold: 1
              timeoutSeconds: 1
            livenessProbe:
              failureThreshold: 10
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              periodSeconds: 20
              successThreshold: 1
              timeoutSeconds: 1
          terminationGracePeriodSeconds: 75
          volumes:
          - emptyDir: {}
            name: keystore-volume

  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: ${APP_NAME}-source
    spec:
      type: git
      params:
      - name: url
        value: ${GIT_REPOSITORY}
      - name: revision
        value: ${GIT_BRANCH}

  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: ${APP_NAME}-image
    spec:
      type: image
      params:
      - name: url
        value: "image-registry.openshift-image-registry.svc:5000/rating/${APP_NAME}:latest"

  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: ${APP_NAME}-image-rc
    spec:
      type: image
      params:
      - name: url
        value: "image-registry.openshift-image-registry.svc:5000/rating/${APP_NAME}:rc"

  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: ${APP_NAME}-pipeline-run
    spec:
      pipelineRef: build-and-deploy
      params:
      - name: appName
        value: ${APP_NAME}
      resources:
      - name: appSource
        resourceRef:
          name: ${APP_NAME}-source
      - name: appImage
        resourceRef:
          name: ${APP_NAME}-image

parameters:
  -
    description: "Name of the deployable application."
    displayName: "Application Name"
    name: APP_NAME
    required: true
  -
    description: "Git repository for source code."
    displayName: "Git Repo"
    name: GIT_REPOSITORY
    required: true
  -
    description: "Git repository branch to build app from"
    displayName: "Git Branch"
    name: GIT_BRANCH
    required: true
    value: master
  -
    description: "Name of the secret for Git credentials."
    displayName: "Build Secret"
    name: BUILD_SECRET
    required: true
    value: git-secret
    
